name: mythicwanderings
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74949
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a0939c'
    - '#776f7a'
    - '#2d3a30'
    - '#76bc7d'
    - '#d6f1e0'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
